# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    profiles:
        active: prod
        include: swagger,no-liquibase
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1:3306/fiesta_iot_rr?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: fiesta
        password: fiesta
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true
    jmx:
        enabled: true
        default-domain: testbedRegistryMBean
        server: testbedRegistryMBean

liquibase:
    contexts: prod

server:
    port: 8084
    contextPath: /ui.testbed-registry
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# fiesta specific properties
# ===================================================================

fiesta:
    enpoints:
        iotRegisterResourceUrl: http://localhost:8080/iot-registry/api/resources
        iotRegisterTestbedUrl: http://localhost:8080/iot-registry/api/testbeds/
        iotRegisterTextUrl: http://localhost:8080/annotator/api/testbed
        ontologyValidatrorObservationUrl: http://localhost:8080/ontologyValidator/Observations
        ontologyValidatorResourceUrl: http://localhost:8080/ontologyValidator/Resources
        authenticateUrl: https://platform.fiesta-iot.eu/openam/json/authenticate
        getUserInfoUrl: https://platform.fiesta-iot.eu/openam/json/users/
        getUserIdUrl: https://platform.fiesta-iot.eu/openam/json/users?_action=idFromSession
        ontologyM3LiteUrl: http://ontology.fiesta-iot.eu/ontologyDocs/m3-lite.owl
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: d2cacc1e057bfb42b1745cd4b0de146bd769a848
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific FIESTA mail property, for standard properties see MailProperties
        from: TestbedRegistry@localhost
        baseUrl: http://my-server-url-to-change # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: TestbedRegistry
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
