version: '2'
services:
    testbedregistry-app:
        image: testbedregistry
        external_links:
            - testbedregistry-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testbedregistry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - FIESTA_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testbedregistry-mysql:
        extends:
            file: mysql.yml
            service: testbedregistry-mysql
