version: '2'
services:
    testbedregistry-mysql:
        container_name: testbedregistry-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/FIESTA/TestbedRegistry/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=testbedregistry
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
